### ISSUE TITLE
Create the necessary projects for the Db foundation

### ISSUE THREAD

**Issue by hailstorm75** [SparesManual/MotorcycleManual#1]
**Libraries**
- `Db.API`
- `Db.Core`
- `Db.Infrastructure`

**Description**
Create the necessary project structure

**Sub-tasks**

- [x] Create the projects
- [x] Enable code analysis
- [x] Set-up build paths
- [x] Include necessary references
