### ISSUE TITLE
Add keyword-based search support

### ISSUE THREAD

**Issue by hailstorm75** [SparesManual/MotorcycleManual#16]
# Libraries affected by the enhancement
 - `Db.API`
 - `Db.Interfaces`
 - `MRI.Db`

# Task goal
The database entities will have a new property containing a list of keywords, based on which user-entered search queries will filter the content of the database. This will solve British and American English inconsistencies. 

# Sub-tasks
 - [x] Enhance the database entities
 - [x] Update the seed data
 - [x] Update the data seeder
 - [x] Update the query specifications
