### ISSUE TITLE
Add sorting support

### ISSUE THREAD

**Issue by hailstorm75** [SparesManual/MotorcycleManual#21]
# Libraries affected by the enhancement
 - `Db.Interfaces`
 - `Db.API`
 - `Db.Infrastructure`
 - `MRI.Db`

# Description
Enhance the API to allow query result sorting on given properties

# Sub-tasks
 - [ ] Come up with a feasible solution
 - [ ] Enhance the server-side API
 - [ ] Enhance the client-side API
