### ISSUE TITLE
Implement account verification

### ISSUE THREAD

**Issue by hailstorm75** [SparesManual/MotorcycleManual#26]
# Requirements
 - #25 Emailing API

# Description
Implement account verification via user emails.

If a user does not verify their account in a given period, delete it. 

# Sub-tasks
 - [x] Create an email confirmed page
 - [x] Enable verification requirement
 - [x] Add logic for sending the verification email
 - [x] Modify login page to prevent authentication if not confirmed
 - [x] Modify login page to resend verification email
