### ISSUE TITLE
Enhance the API to return ImagePoints

### ISSUE THREAD

**Issue by hailstorm75** [SparesManual/MotorcycleManual#31]
# Libraries affected by the enhancement
 - `MRI.Db`
 - `Db.API`

# Description
The API must provide a way to receive points of parts depicted on an image of a given section.

# Sub-tasks
 - [x] Create the model
 - [x] Create the specification
 - [x] Create the server-side method
 - [x] Create the client-side method
